# Standards: 2.6
---
# centos7 goodies + extras
- hosts: localhost
  become: yes
  become_method: su
  remote_user: root
  become_user: root
  connection: local
  tasks:
  - include: roles/common/tasks/update.yml
