# Standards: 2.6
---
# local.yml catch-all playbook
- hosts: localhost
  become: yes
  become_method: su
  remote_user: root
  become_user: root
  connection: local
  tasks:
    - include: roles/common/tasks/update.yml
    - include: roles/common/tasks/upgrade.yml
    - include: roles/common/tasks/cleanup.yml
   - include: roles/common/tasks/repo/chrome.yml
   - include: roles/common/tasks/repo/typora.yml
   - include: roles/common/tasks/repo/all-combined.yml
   - include: roles/common/tasks/apt-install.yml
   - include: roles/common/tasks/pip.yml
   - include: roles/common/tasks/snap/google-play.yml
   - include: roles/common/tasks/spideroak.yml
   - include: roles/common/tasks/repo/sublimetext.yml
   - include: roles/common/tasks/tlp.yml
   - include: roles/common/tasks/ssh-permissions.yml
   - include: roles/common/tasks/bash.yml
   - include: roles/common/tasks/vim-runtime.yml
   - include: roles/common/tasks/vim.yml
    - include: roles/common/tasks/update.yml
    - include: roles/common/tasks/upgrade.yml
    - include: roles/common/tasks/cleanup.yml
    - include: tasks/dropbox-setup.yml
    - include: tasks/update.yml
    - include: tasks/upgrade.yml
    - include: tasks/cleanup.yml
    - include: tasks/repo/all-combined.yml
    - include: tasks/apt-install.yml
