# Standards: 2.6
---
# test.yml - testing & tests playbook
- hosts: localhost
  become: yes
  become_method: su
  remote_user: root
  become_user: root
  connection: local
  tasks:
  - include: roles/common/tasks/update.yml
  - include: roles/common/tasks/upgrade.yml
  - include: roles/common/tasks/snap/snapd.yml
  - include: roles/common/tasks/cleanup.yml
