# Standards: 2.6
---
# test.yml - testing & tests playbook
- hosts: localhost
  become: yes
  become_method: su
  remote_user: root
  become_user: root
  connection: local
  tasks:
  - include: update.yml
  - include: roles/common/tasks/deb/atom.yml
  # - include: roles/common/tasks/copy-test.yml
