# Standards: 2.6
---
# test.yml - testing & tests playbook
- hosts: localhost
  become: yes
  become_method: su
  remote_user: root
  become_user: root
  connection: local
  tasks:
  - include: roles/common/tasks/update.yml
  - include: roles/common/tasks/upgrade.yml
  - include: roles/common/tasks/cleanup.yml
  # - include: tasks/dropbox-setup.yml
  - include: roles/tasks/update.yml
  - include: roles/tasks/upgrade.yml
  - include: roles/tasks/cleanup.yml
  - include: roles/tasks/repo/all-combined.yml
  - include: roles/tasks/apt-install.yml
