# Standards: 2.7
---
# ubuntu-workstation.yml ubuntu desktop workstation playbook
- hosts: localhost
  become: yes
  become_method: su
  remote_user: root
  become_user: root
  connection: local
  tasks:
  - include: roles/common/tasks/update.yml
