# Standards: 2.6
---
# ubuntu-mediacenter.yml mediacenter playbook (Kodi/FFMPEG/VLC/MPV)
- hosts: localhost
  become: yes
  become_method: su
  remote_user: root
  become_user: root
  connection: local
  tasks:
  - include: roles/common/tasks/update.yml
