# Standards: 2.7
---
# update.yml universal updater playbook
- hosts: localhost
  become: yes
  become_method: su
  remote_user: root
  become_user: root
  connection: local
  tasks:
  - include: roles/common/tasks/update.yml
  - include: roles/common/tasks/upgrade.yml
  - include: roles/common/tasks/cleanup.yml
