# Standards: 2.6
---
# remote-desktop playbook (xfce)
- hosts: localhost
  become: yes
  become_method: su
  remote_user: root
  become_user: root
  connection: local
  tasks:
  - include: roles/common/tasks/update.yml
  - include: roles/common/tasks/xfce-desktop.yml
  - include: roles/common/tasks/restricted-extras.yml
  - include: roles/common/tasks/external-ip.yml
  - include: roles/common/tasks/cleanup.yml
  - include: roles/common/tasks/nomachine.yml
