# Standards: 2.7
---
# turn off command warnings for ansible
- name: turn off command warnings for ansible
  lineinfile:
    dest: /etc/ansible/ansible.cfg
    regexp: ''
    insertafter: EOF
    line: 'command_warnings=False'
    create: yes
