- name: touch "~/.vimrc"
  command: touch "~/.vimrc"

- name: stat .vimrc
  stat: path="~/.vimrc"
  register: vimrc_stat

- name: Move vimrc to vimrc.original
  command: mv "~/.vimrc" "~/vimrc.original"

- name: download vimrc
  get_url:
    url:  "https://raw.githubusercontent.com/myersg86/dotfiles/master/.vimrc"
    dest: "~/."
