# Standards: 2.6
---
# Install xfce4 desktop & xfce-goodies
- name: install xfce4 desktop & xfce-goodies packages
  apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
  become: yes
  with_items:
  - xfce4
  - xfce4-goodies
